### ISSUE TITLE
Lead at End

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#163]
The HTML5 Active Form needs to support the "lead at end" option in the AW admin:

![image](https://cloud.githubusercontent.com/assets/1377228/5821081/1648a3b0-a08f-11e4-943e-7b1f40ed9999.png)

When the "Add at End of Pageflow" box is checked, the page led to should be inserted as the last page in the form.  If there are multiple "lead at end" actions, they just stack up at the end.  Essentially, these pages are treated as new required pages at the end of the flow path.

**Comment by gsteimer** [comment]
See the screencam below.  Pages 9 and 10 are incorrectly inserted before pg7:

![lead-at-end](https://cloud.githubusercontent.com/assets/1377228/5821962/a48146fe-a095-11e4-9fb4-01a7ad204e45.gif)

**Comment by mikeblum** [comment]
This is a supported feature. Changing to issue. When fixing this, verify it works with #164.

**Comment by mikeblum** [comment]
TS Leading actions passed. I think this is fixed now: #164

**Comment by gsteimer** [comment]
This is still not working on edge1 - see the screencam below.  I'm not too worried about this since we don't have a client form using the Lead at End functionality...

![lead-at-end](https://cloud.githubusercontent.com/assets/1377228/5960031/3c58bf4e-a798-11e4-93c5-c41cc6e913cb.gif)

**Comment by mikeblum** [comment]
Revision: 11651
Author: mblum
Date: 2015-01-30 12:21:41.773249
LEAD At END: Wizard - fix adding a page to the end of a form implementation. Should support Lead to end page owning another child page. Vancant Properties form proves this out. 

M   /trunk/code/test/tests/modules/wizard/wizard/flowpathSpec.js
M   /trunk/code/app/modules/wizard/models/flowpath.js
M   /trunk/code/test/tests/modules/wizard/services/pagesetinstanceproviderSpec.js
M   /trunk/code/app/modules/wizard/services/pagesetinstanceprovider.js
